CREATE TABLE ingredient (
    id bigint NOT NULL,
    category character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    name character varying(50) NOT NULL
);

ALTER TABLE ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE member (
    id bigint NOT NULL,
    activity_level character varying(20),
    age integer,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    gender character varying(10),
    height numeric(38,2),
    login_id character varying(20) NOT NULL,
    nickname character varying(10) NOT NULL,
    password character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    weight numeric(38,2),
    CONSTRAINT member_activity_level_check CHECK (((activity_level)::text = ANY ((ARRAY['LOW'::character varying, 'LIGHT'::character varying, 'MODERATE'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT member_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying])::text[])))
);

ALTER TABLE member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE member_ingredient (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    ingredient_id bigint NOT NULL,
    member_id bigint NOT NULL
);

ALTER TABLE member_ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME member_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE recipe (
    id bigint NOT NULL,
    calorie numeric(38,2) NOT NULL,
    carbohydrate numeric(38,2) NOT NULL,
    category character varying(20) NOT NULL,
    cooking_method character varying(20) NOT NULL,
    cooking_steps text NOT NULL,
    fat numeric(38,2) NOT NULL,
    image_url character varying(255),
    ingredient_raw_text text NOT NULL,
    name character varying(50) NOT NULL,
    protein numeric(38,2) NOT NULL,
    sodium numeric(38,2) NOT NULL
);

ALTER TABLE recipe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME recipe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE recipe_ingredient (
    id bigint NOT NULL,
    ingredient_id bigint NOT NULL,
    recipe_id bigint NOT NULL
);

ALTER TABLE recipe_ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME recipe_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY ingredient
    ADD CONSTRAINT ingredient_pkey PRIMARY KEY (id);

ALTER TABLE ONLY member_ingredient
    ADD CONSTRAINT member_ingredient_pkey PRIMARY KEY (id);

ALTER TABLE ONLY member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);

ALTER TABLE ONLY recipe_ingredient
    ADD CONSTRAINT recipe_ingredient_pkey PRIMARY KEY (id);

ALTER TABLE ONLY recipe
    ADD CONSTRAINT recipe_pkey PRIMARY KEY (id);

ALTER TABLE ONLY recipe_ingredient
    ADD CONSTRAINT uk58ocuab26seiw3rx6gd3eh4dn UNIQUE (recipe_id, ingredient_id);

ALTER TABLE ONLY ingredient
    ADD CONSTRAINT ukbcuaj97y3iu3t2vj26jg6hijj UNIQUE (name);

ALTER TABLE ONLY member
    ADD CONSTRAINT ukenfm5patwjqulw8k4wwuo6f60 UNIQUE (login_id);

ALTER TABLE ONLY member_ingredient
    ADD CONSTRAINT ukjjleklx2o6ma0cs8jg23xdh9k UNIQUE (member_id, ingredient_id);

ALTER TABLE ONLY member
    ADD CONSTRAINT ukmbmcqelty0fbrvxp1q58dn57t UNIQUE (email);

CREATE INDEX idxhvk7mme88fvl8jcr0onwxidcu ON member_ingredient USING btree (ingredient_id);

CREATE INDEX idxtmcdw7h1sgbnmr3tab1ccbb49 ON recipe_ingredient USING btree (ingredient_id);

ALTER TABLE ONLY recipe_ingredient
    ADD CONSTRAINT fk9b3oxoskt0chwqxge0cnlkc29 FOREIGN KEY (ingredient_id) REFERENCES ingredient(id) ON DELETE CASCADE;

ALTER TABLE ONLY recipe_ingredient
    ADD CONSTRAINT fkgu1oxq7mbcgkx5dah6o8geirh FOREIGN KEY (recipe_id) REFERENCES recipe(id) ON DELETE CASCADE;

ALTER TABLE ONLY member_ingredient
    ADD CONSTRAINT fkm6tm9v7e8esq5ru6wen99312m FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE;

ALTER TABLE ONLY member_ingredient
    ADD CONSTRAINT fkrofa19yuusq97ik5baidiwcot FOREIGN KEY (ingredient_id) REFERENCES ingredient(id) ON DELETE CASCADE;
