ALTER TABLE recipe ALTER COLUMN calorie DROP NOT NULL;
ALTER TABLE recipe ALTER COLUMN carbohydrate DROP NOT NULL;
ALTER TABLE recipe ALTER COLUMN protein DROP NOT NULL;
ALTER TABLE recipe ALTER COLUMN fat DROP NOT NULL;
ALTER TABLE recipe ALTER COLUMN sodium DROP NOT NULL;
