CREATE TABLE member_saved_meal (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    member_id bigint NOT NULL,
    recipe_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT member_saved_meal_pkey PRIMARY KEY (id),
    CONSTRAINT uk_member_saved_meal_member_recipe UNIQUE (member_id, recipe_id),
    CONSTRAINT fk_member_saved_meal_member FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT fk_member_saved_meal_recipe FOREIGN KEY (recipe_id) REFERENCES recipe(id) ON DELETE RESTRICT
);

CREATE INDEX idx_member_saved_meal_recipe ON member_saved_meal USING btree (recipe_id);
